# Generated by Django 6.0.2 on 2026-03-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_created_at_payment_payment_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("bank_transfer", "Перевод на счет"),
                    ("card", "Карта (Stripe)"),
                ],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
