# Generated by Django 6.0.2 on 2026-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Превью",
                null=True,
                upload_to="materials/previews/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание курса",
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Превью",
                null=True,
                upload_to="materials/previews/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(
                help_text="Введите название курса",
                max_length=255,
                verbose_name="Название курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(
                help_text="Введите название урока",
                max_length=255,
                verbose_name="Название урока",
            ),
        ),
    ]
