# Generated by Django 6.0.2 on 2026-03-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_coursesubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=10, max_digits=8, verbose_name="Цена курса"
            ),
        ),
    ]
